services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - notifications_redis_data:/bitnami/redis/data

volumes:
  notifications_redis_data:
